/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.Analyst;
import entities.Department;
import entities.Director;
import entities.Employee;
import entities.Janitor;
import entities.Manager;
import entities.Programmer;
import entities.Salary;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import resources.TableDepDirectors;
import resources.TableDepartments;
import resources.Validation;

/**
 *
 * @author TUNTS
 */
public class NewEmployee extends javax.swing.JFrame {

    private SystemHR calledBy = null;
    private List<Department> departments = new ArrayList();
    private List<Department> deps = new ArrayList();
    private String[] combo;
    private List<String> notNullDepartments = new ArrayList();
    private String[] comboMan;
    boolean name, surname, rg, cpf, password, allValid;
    private boolean[] validate = {name, surname, rg, cpf, password};
    private String[] sValidate = {"nome", "sobrenome", "rg", "cpf", "password"};

    /**
     * Creates new form NewEmployee
     */
    public NewEmployee(SystemHR calledBy) {

        this.calledBy = calledBy;

        this.departments = Department.getAll();
        int size = departments.size();
        this.combo = new String[size];

        for (int i = 0; i < size; i++) {
            Department dep;
            dep = departments.get(i);
            this.combo[i] = dep.getName();
        }

        for (Department d : departments) {
            if (d.getManager().getIdManager() == 0) {
                this.notNullDepartments.add(d.getName());
            }
        }

        this.comboMan = new String[notNullDepartments.size()];

        for (int i = 0; i < notNullDepartments.size(); i++) {
            this.comboMan[i] = notNullDepartments.get(i);
        }

        initComponents();

        cbEmpLevel.setEnabled(true);
        setManagerEnable(false);
        setDirectorEnable(true);

    }

    private NewEmployee() {

        this.departments = Department.getAll();
        int size = departments.size();
        this.combo = new String[size];

        for (int i = 0; i < size; i++) {
            Department dep;
            dep = departments.get(i);
            this.combo[i] = dep.getName();
        }

        for (Department d : departments) {
            if (d.getManager().getIdManager() == 0) {
                this.notNullDepartments.add(d.getName());
            }
        }

        this.comboMan = new String[notNullDepartments.size()];

        for (int i = 0; i < notNullDepartments.size(); i++) {
            this.comboMan[i] = notNullDepartments.get(i);
        }

        initComponents();

        cbEmpLevel.setEnabled(true);
        setManagerEnable(false);
        setDirectorEnable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEmpName = new javax.swing.JLabel();
        tfEmpName = new javax.swing.JTextField();
        tfEmpSurname = new javax.swing.JTextField();
        tfEmpRG = new javax.swing.JTextField();
        lbEmpSurname = new javax.swing.JLabel();
        lbEmpRG = new javax.swing.JLabel();
        lbEmpCPF = new javax.swing.JLabel();
        lbEmpPassword = new javax.swing.JLabel();
        lbEmpPhone = new javax.swing.JLabel();
        lbEmpPasswordConfirm = new javax.swing.JLabel();
        cbEmpOffice = new javax.swing.JComboBox();
        cbEmpDepartment = new javax.swing.JComboBox();
        lbEmpOffice = new javax.swing.JLabel();
        lbEmpDepartment = new javax.swing.JLabel();
        cbEmpLevel = new javax.swing.JComboBox();
        lbEmpLevel = new javax.swing.JLabel();
        btCancelNewEmp = new javax.swing.JButton();
        btSaveNewEmp = new javax.swing.JButton();
        lbSystemTitle = new javax.swing.JLabel();
        pnManager = new javax.swing.JPanel();
        cbEmpDep = new javax.swing.JComboBox();
        pnDirector = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDeps = new javax.swing.JTable();
        btGoIn = new javax.swing.JButton();
        btGoOut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDepsDirector = new javax.swing.JTable();
        tfEmpCPF = new javax.swing.JFormattedTextField();
        tfEmpPhone = new javax.swing.JFormattedTextField();
        tfEmpPassword = new javax.swing.JPasswordField();
        tfEmpPasswordConfirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbEmpName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpName.setText("Nome");

        tfEmpName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmpNameKeyPressed(evt);
            }
        });

        tfEmpSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmpSurnameKeyPressed(evt);
            }
        });

        tfEmpRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmpRGKeyPressed(evt);
            }
        });

        lbEmpSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpSurname.setText("Sobrenome");

        lbEmpRG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpRG.setText("RG");

        lbEmpCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpCPF.setText("CPF");

        lbEmpPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpPassword.setText("Senha");

        lbEmpPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpPhone.setText("Telefone");

        lbEmpPasswordConfirm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpPasswordConfirm.setText("Confirmar Senha");

        cbEmpOffice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diretor", "Gerente", "Analista", "Programador", "Auxiliar de Limpeza" }));
        cbEmpOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmpOfficeActionPerformed(evt);
            }
        });

        cbEmpDepartment.setModel(new javax.swing.DefaultComboBoxModel(this.combo));

        lbEmpOffice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpOffice.setText("Cargo");

        lbEmpDepartment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpDepartment.setText("Departamento");

        cbEmpLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        lbEmpLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmpLevel.setText("Nível");

        btCancelNewEmp.setText("Cancelar");
        btCancelNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelNewEmpActionPerformed(evt);
            }
        });

        btSaveNewEmp.setText("Salvar");
        btSaveNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveNewEmpActionPerformed(evt);
            }
        });

        lbSystemTitle.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbSystemTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSystemTitle.setText("Novo Funcionário");

        pnManager.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções de Gerente - Departamento Gerenciado"));

        cbEmpDep.setModel(new javax.swing.DefaultComboBoxModel(this.comboMan));

        javax.swing.GroupLayout pnManagerLayout = new javax.swing.GroupLayout(pnManager);
        pnManager.setLayout(pnManagerLayout);
        pnManagerLayout.setHorizontalGroup(
            pnManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEmpDep, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnManagerLayout.setVerticalGroup(
            pnManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEmpDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDirector.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções de Diretor - Departamentos Dirigidos"));

        tbDeps.setModel(new TableDepartments());
        tbDeps.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbDeps);

        btGoIn.setText("►");
        btGoIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGoInActionPerformed(evt);
            }
        });

        btGoOut.setText("◄");
        btGoOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGoOutActionPerformed(evt);
            }
        });

        tbDepsDirector.setModel(new TableDepDirectors(deps));
        tbDepsDirector.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbDepsDirector);

        javax.swing.GroupLayout pnDirectorLayout = new javax.swing.GroupLayout(pnDirector);
        pnDirector.setLayout(pnDirectorLayout);
        pnDirectorLayout.setHorizontalGroup(
            pnDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDirectorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btGoOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGoIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        pnDirectorLayout.setVerticalGroup(
            pnDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDirectorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDirectorLayout.createSequentialGroup()
                        .addComponent(btGoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btGoOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tfEmpCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmpCPFFocusGained(evt);
            }
        });

        tfEmpPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmpPhoneFocusGained(evt);
            }
        });

        tfEmpPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmpPasswordKeyReleased(evt);
            }
        });

        tfEmpPasswordConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmpPasswordConfirmKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbEmpSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbEmpRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbEmpCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbEmpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbEmpOffice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfEmpRG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                        .addComponent(tfEmpSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(cbEmpOffice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbEmpLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbEmpLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(tfEmpCPF)
                                        .addComponent(tfEmpPhone)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbEmpPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbEmpPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbEmpDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbEmpDepartment, 0, 332, Short.MAX_VALUE)
                                    .addComponent(tfEmpPassword)))
                            .addComponent(lbSystemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSaveNewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCancelNewEmp))
                            .addComponent(pnDirector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnManager, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(tfEmpPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSystemTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpName)
                    .addComponent(tfEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmpSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmpSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmpRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmpRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpCPF)
                    .addComponent(tfEmpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpPhone)
                    .addComponent(tfEmpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEmpOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmpOffice)
                    .addComponent(cbEmpLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmpLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEmpDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmpDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpPassword)
                    .addComponent(tfEmpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpPasswordConfirm)
                    .addComponent(tfEmpPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(pnManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelNewEmp)
                    .addComponent(btSaveNewEmp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveNewEmpActionPerformed
        validate[3] = Validation.validarCpf(tfEmpCPF.getText());
        
        for (int i = 0; i < validate.length; i++) {
            if (!validate[i]) {
                allValid = false;
                JOptionPane.showMessageDialog(null, "Preeencha corretamente o campo "+sValidate[i]+".");
                break;
            }
        }
        
        
                
        if (allValid) {
            int idOffice = cbEmpOffice.getSelectedIndex();

            Employee[] classes = {new Director(), new Manager(), new Analyst(), new Programmer(), new Janitor()};
            Employee emp = classes[idOffice];
            emp.setSalary(new Salary());

            switch (cbEmpOffice.getSelectedIndex()) {
                case 0:
                    emp.setDeps(deps);
                    break;
                case 1:
                    emp.setDep(departments.get(cbEmpDep.getSelectedIndex()));
                    break;
                case 4:
                    cbEmpLevel.setSelectedIndex(0);
                    break;
            }

            emp.setName(tfEmpName.getText());
            emp.setSurname(tfEmpSurname.getText());
            emp.setRG(tfEmpRG.getText());
            emp.setCPF(tfEmpCPF.getText());
            emp.setPhone(tfEmpPhone.getText());
            emp.getSalary().setIdOffice(cbEmpOffice.getSelectedIndex());
            emp.getSalary().setLevel(cbEmpLevel.getSelectedIndex());
            emp.setPassword(new String(tfEmpPassword.getPassword()));
            emp.setDepartment(departments.get(cbEmpDepartment.getSelectedIndex()));

            emp.add();

            this.dispose();
            calledBy.setEnabled(true);
        }
    }//GEN-LAST:event_btSaveNewEmpActionPerformed

    private void btCancelNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelNewEmpActionPerformed
        this.dispose();
        calledBy.setEnabled(true);
    }//GEN-LAST:event_btCancelNewEmpActionPerformed

    private void cbEmpOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmpOfficeActionPerformed

        int selectedItem = cbEmpOffice.getSelectedIndex();

        boolean[][] permissions
                = {
                    //     Level / Manager / Director
                    {true, false, true}, // Director
                    {true, true, false}, // Manager
                    {true, false, false}, // Analistic
                    {true, false, false}, // Programmer
                    {false, false, false} // Janitor
                };

        cbEmpLevel.setEnabled(permissions[selectedItem][0]);
        setManagerEnable(permissions[selectedItem][1]);
        setDirectorEnable(permissions[selectedItem][2]);
    }//GEN-LAST:event_cbEmpOfficeActionPerformed

    private void btGoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGoInActionPerformed

        int rows[] = tbDeps.getSelectedRows();
        ((TableDepartments) tbDeps.getModel()).remove(rows, deps);
        tbDepsDirector.setModel(new TableDepDirectors(deps));

    }//GEN-LAST:event_btGoInActionPerformed

    private void btGoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGoOutActionPerformed

        int rows[] = tbDepsDirector.getSelectedRows();
        List<Department> departs = ((TableDepDirectors) tbDepsDirector.getModel()).remove(rows);
        ((TableDepartments) tbDeps.getModel()).addToList(departs);


    }//GEN-LAST:event_btGoOutActionPerformed

    private void tfEmpNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmpNameKeyPressed
        validate[0] = Validation.validateTextField(tfEmpName);        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmpNameKeyPressed

    private void tfEmpSurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmpSurnameKeyPressed
        validate[1] = Validation.validateTextField(tfEmpSurname);
    }//GEN-LAST:event_tfEmpSurnameKeyPressed

    private void tfEmpRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmpRGKeyPressed
        validate[2] = Validation.validateNumberField(tfEmpRG);
    }//GEN-LAST:event_tfEmpRGKeyPressed

    private void tfEmpCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmpCPFFocusGained
        try {
            Validation.maskCPF(tfEmpCPF);
        } catch (ParseException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tfEmpCPFFocusGained

    private void tfEmpPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmpPhoneFocusGained
        try {
            Validation.maskPhone(tfEmpPhone);
        } catch (ParseException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_tfEmpPhoneFocusGained

    private void tfEmpPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmpPasswordKeyReleased
        validate[4] = Validation.checkPassword(tfEmpPassword, tfEmpPasswordConfirm);
    }//GEN-LAST:event_tfEmpPasswordKeyReleased

    private void tfEmpPasswordConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmpPasswordConfirmKeyReleased
        validate[4] = Validation.checkPassword(tfEmpPassword, tfEmpPasswordConfirm);
    }//GEN-LAST:event_tfEmpPasswordConfirmKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        calledBy.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    public void setManagerEnable(boolean status) {
        Component[] manager = pnManager.getComponents();
        for (int i = 0; i < manager.length; i++) {
            manager[i].setEnabled(status);
        }
    }

    public void setDirectorEnable(boolean status) {
        Component[] director = pnDirector.getComponents();
        for (int i = 0; i < director.length; i++) {
            director[i].setEnabled(status);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelNewEmp;
    private javax.swing.JButton btGoIn;
    private javax.swing.JButton btGoOut;
    private javax.swing.JButton btSaveNewEmp;
    private javax.swing.JComboBox cbEmpDep;
    private javax.swing.JComboBox cbEmpDepartment;
    private javax.swing.JComboBox cbEmpLevel;
    private javax.swing.JComboBox cbEmpOffice;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbEmpCPF;
    private javax.swing.JLabel lbEmpDepartment;
    private javax.swing.JLabel lbEmpLevel;
    private javax.swing.JLabel lbEmpName;
    private javax.swing.JLabel lbEmpOffice;
    private javax.swing.JLabel lbEmpPassword;
    private javax.swing.JLabel lbEmpPasswordConfirm;
    private javax.swing.JLabel lbEmpPhone;
    private javax.swing.JLabel lbEmpRG;
    private javax.swing.JLabel lbEmpSurname;
    private javax.swing.JLabel lbSystemTitle;
    private javax.swing.JPanel pnDirector;
    private javax.swing.JPanel pnManager;
    private javax.swing.JTable tbDeps;
    private javax.swing.JTable tbDepsDirector;
    private javax.swing.JFormattedTextField tfEmpCPF;
    private javax.swing.JTextField tfEmpName;
    private javax.swing.JPasswordField tfEmpPassword;
    private javax.swing.JPasswordField tfEmpPasswordConfirm;
    private javax.swing.JFormattedTextField tfEmpPhone;
    private javax.swing.JTextField tfEmpRG;
    private javax.swing.JTextField tfEmpSurname;
    // End of variables declaration//GEN-END:variables
}
